### ISSUE TITLE
What is this project licensed under?

### ISSUE THREAD

**Issue by lukefwilson** [xevojapan/h264-converter#15]
Hello,

I'm investigating using this library for a project of mine, but want to ensure it's available under on open source license. I don't see any license in the repo at the moment. I see it as MIT [on npm](https://www.npmjs.com/package/h264-converter?activeTab=readme). Any chance you can add the MIT license to this repo as well?

Thank you!!

**Comment by horiuchi** [comment]
@lukefwilson Thanks for your interest in this project.

I've added a LICENSE file to state the MIT license clearly.
I don't maintain it anymore but feel free to use it.
